blog/urls.py
from django.urls import path, re_path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blog/list/', views.post_list, name='post_list'),
    re_path(r'^tag/(?P<tag_slug>[\w-]+)/$', views.post_list, name='post_list_by_tag'),
    re_path(r'^detail/(?P<post_slug>[\w-]+)/$', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('about/', views.about_me_page, name='about_me_page'),
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
sitemaps = {
    'posts': PostSitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemap')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from django.contrib.auth.models import User
from django.urls import reverse
from extensions.utils import jalali_converter
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCountMixin, HitCount
from taggit.managers import TaggableManager


# Create your models here.

class HomeBanner(models.Model):
    hello = models.CharField(max_length=100)
    who_am_i = models.CharField(max_length=200)
    education = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='HomeBanner/', default='home-right.png')
    cv_button = models.CharField(max_length=50)
    cv_file = models.FileField(upload_to='cv/')
    contact_me_button = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'greeting'

    def __str__(self):
        return self.who_am_i


class AboutMe(models.Model):
    title = models.CharField(max_length=200)
    body = HTMLField()
    picture = models.ImageField(upload_to='AboutMe/')

    def __str__(self):
        return self.title


class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model, HitCountMixin):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, allow_unicode=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    body = HTMLField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishManager()
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
                                        related_query_name='hit_count_generic_relation')
    tags = TaggableManager()
    quotes = HTMLField(default='')
    image_one = models.ImageField(upload_to='post_image/', default='')
    image_two = models.ImageField(upload_to='post_image/', default='')

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=('-publish',))
        ]

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    def jpublish(self):
        return jalali_converter(self.publish)

    def __str__(self):
        return self.title


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, verbose_name=': نام شما')
    email = models.EmailField(verbose_name=': ایمیل')
    body = models.TextField(verbose_name=': متن مورد نظر')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True, )

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import PostComment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=80, label='نام خود را وارد کنید',
                           widget=forms.TextInput(attrs={'class': 'form-control form text-right'}))
    email = forms.EmailField(label='ایمیل خود را وارد کنید',
                             widget=forms.EmailInput(attrs={'class': 'form-control text-right'}))
    to = forms.EmailField(label='ایمیل خود را وارد کنید',
                          widget=forms.EmailInput(attrs={'class': 'form-control text-right'}))
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control text-right'}),
                               label='متن نظر خود را وارد کنید')


class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ['name', 'email', 'body']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control text-right', 'placeholder': 'نام خود را وارد کنید'}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control text-right', 'placeholder': 'ایمیل خود را وارد کنید'}),
            'body': forms.Textarea(
                attrs={'class': 'form-control text-right', 'placeholder': 'متن نظر خود را وارد کنید'}),

        }


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, PostComment, HomeBanner, AboutMe
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity


# Create your views here.
def index(request):
    main = get_object_or_404(HomeBanner)
    about_me = get_object_or_404(AboutMe)
    context = {
        'main': main,
        'about_me': about_me
    }
    return render(request, 'blog/index/index.html', context)


def about_me_page(request):
    return render(request, 'blog/index/about.html')


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug, )
        post_list = post_list.filter(tags__in=[tag])
    for post in post_list:
        post.total_comments = post.comments.count()
    # Pagination with 3 post pre page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page')
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    all_tags = Tag.objects.filter(post__in=post_list).distinct()
    context = {
        'posts': posts,
        'tag': tag,
        'all_tags': all_tags

    }
    return render(request, 'blog/post/list.html', context)


def post_detail(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', 'publish')[:4]
    comment_count = comments.count()
    # Check if 'INSERT_IMAGE_HERE' exists in the content
    if 'INSERT_IMAGE_HERE' in post.body:
        # Split the body into two parts based on the 'INSERT_IMAGE_HERE' marker
        body_parts = post.body.split('INSERT_IMAGE_HERE')
        content_before_image = body_parts[0]  # Content before the image
        content_after_image = body_parts[1]  # Content after the image
        has_image = True
    else:
        content_before_image = post.body
        content_after_image = None
        has_image = False
    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'similar_posts': similar_posts,
        'comment_count': comment_count,
        'content_before_image': content_before_image,
        'content_after_image': content_after_image,
        'has_image': has_image,
    }
    return render(request, 'blog/post/2.html', context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'codepython3.12@gmail.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'post': post,
        'form': form,
        'sent': sent,
    }
    return render(request, 'blog/post/share.html', context)


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    context = {
        'post': post,
        'form': form,
        'comment': comment,
    }
    return render(request, 'blog/post/comment.html', context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(similarity=TrigramSimilarity('title', query), ).filter(
                similarity__gt=0.1).order_by('-similarity')
    context = {
        'form': form,
        'query': query,
        'results': results
    }
    return render(request, 'blog/post/search.html', context)

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form class="comment-form" action="{% url "blog:post_comment" post.id %}" method="post">
    <div class="form-group">
        {{ form.as_p }}
        {% csrf_token %}
    </div>
    <p><input role="button" type="submit" class="primary-btn primary_btn" value="اضافه کردن نظر">
</form>

blog/templates/blog/post/includes/sidebar.html
{% load blog_tags %}
{% load static %}

<div class="col-lg-4">
    <div class="blog_right_sidebar">
        <aside class="single_sidebar_widget search_widget">
            <div class="input-group text-center">
                <form method="get" action="{% url 'blog:post_search' %}">
                    {% csrf_token %}
                    <input class="form-control text-center" type="text" name="query" placeholder=".....پیدا کردن ">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i>  جست و جو </button>
                    </span>
                </form>
            </div><!-- /input-group -->
            <div class="br"></div>
        </aside>
        <aside class="single_sidebar_widget author_widget">
            <img class="author_img rounded-circle" src="img/blog/author.png" alt="">
            <h4>رانیار رشیدی</h4>
            <p>برنامه نویس جونیور وب</p>
            <div class="social_icon">
                <a href="#"><i class="fab fa-whatsapp"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-telegram"></i></a>
                <a href="#"><i class="fas fa-envelope"></i></a>
            </div>
            <p>سلام به قسمت بلاگ و خبری سایت من خوش امدید. میتونید با سرچ کردن مباحث مورد علاقتون رو پیدا کنید یا با
                کلیک بر روی تگ مورد علاقتون پست های حاو اون تگ رو ببینید.</p>
            <div class="br"></div>
        </aside>
        <aside class="single_sidebar_widget popular_post_widget">
            <p class="widget_title">تعداد کل پست های بلاگ : {% total_posts %}</p>
            <h3 class="widget_title">پست های مشابه</h3>
            <div class="media post_item">
                <div class="media-body">
                    {% for post in similar_posts %}
                        <ul class="list-group p-1 text-right ">
                            <li class="list-group-item  list-unstyled">
                                <a href="{{ post.get_absolute_url }}"><h3>{{ post.title }}</h3></a>
                                <p>{{ post.jpublish }} </p>
                            </li>
                        </ul>
                    {% empty %}
                        <p> پست مشابه وجود ندارد.</p>
                        </div>
                    {% endfor %}
            </div>
        </aside>
{#        <aside class="single_sidebar_widget ads_widget">#}
{#            <a href="#"><img class="img-fluid" src="{% static 'img/blog/add.jpg' %}" alt=""></a>#}
{#            <div class="br"></div>#}
{#        </aside>#}
        <aside class="single_sidebar_widget post_category_widget">
            <h4 class="widget_title">اخرین پست ها</h4>
            <ul class="list cat-list text-right">
                <li>
                    <h3>اخرین پست ها</h3>
                    <p>{% show_latest_posts 4 %}</p>
                </li>
            </ul>
            <div class="br"></div>
        </aside>
        <aside class="single_sidebar_widget post_category_widget">
            <h4 class="widget_title"> بیشترین پست های کامنت دار</h4>
            {% get_most_commented_posts as most_commented_posts %}
            <ul class="list cat-list text-right">
                {% for post in most_commented_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}

            </ul>
            <div class="br"></div>
        </aside>
{#        <aside class="single-sidebar-widget newsletter_widget">#}
{#            <h4 class="widget_title">Newsletter</h4>#}
{#            <p>#}
{#                Here, I focus on a range of items and features that we use in life without#}
{#                giving them a second thought.#}
{#            </p>#}
{#            <div class="form-group d-flex flex-row">#}
{#                <div class="input-group">#}
{#                    <div class="input-group-prepend">#}
{#                        <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>#}
{#                        </div>#}
{#                    </div>#}
{#                    <input type="text" class="form-control" id="inlineFormInputGroup"#}
{#                           placeholder="Enter email" onfocus="this.placeholder = ''"#}
{#                           onblur="this.placeholder = 'Enter email'">#}
{#                </div>#}
{#                <a href="{% url 'blog:post_feed' %}" class="bbtns">Subcribe</a>#}
{#            </div>#}
{#            <p class="text-bottom">You can unsubscribe at any time</p>#}
{#            <div class="br"></div>#}
{##}
{#        </aside>#}
    </div>
</div>