blog/urls.py
from django.urls import path, re_path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blog/list/', views.post_list, name='post_list'),
    re_path(r'^tag/(?P<tag_slug>[\w-]+)/$', views.post_list, name='post_list_by_tag'),
    re_path(r'^detail/(?P<post_slug>[\w-]+)/$', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('about/', views.about_me_page, name='about_me_page'),
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
sitemaps = {
    'posts': PostSitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemap')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from django.contrib.auth.models import User
from django.urls import reverse
from extensions.utils import jalali_converter
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCountMixin, HitCount
from taggit.managers import TaggableManager


# Create your models here.

class HomeBanner(models.Model):
    hello = models.CharField(max_length=100)
    who_am_i = models.CharField(max_length=200)
    education = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='HomeBanner/', default='home-right.png')
    cv_button = models.CharField(max_length=50)
    cv_file = models.FileField(upload_to='cv/')
    contact_me_button = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'greeting'

    def __str__(self):
        return self.who_am_i


class AboutMe(models.Model):
    title = models.CharField(max_length=200)
    body = HTMLField()
    picture = models.ImageField(upload_to='AboutMe/')

    def __str__(self):
        return self.title


class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model, HitCountMixin):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, allow_unicode=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    body = HTMLField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishManager()
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
                                        related_query_name='hit_count_generic_relation')
    tags = TaggableManager()
    quotes = HTMLField(default='')
    image_one = models.ImageField(upload_to='post_image/', default='')
    image_two = models.ImageField(upload_to='post_image/', default='')

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=('-publish',))
        ]

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    def jpublish(self):
        return jalali_converter(self.publish)

    def __str__(self):
        return self.title


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, verbose_name=': نام شما')
    email = models.EmailField(verbose_name=': ایمیل')
    body = models.TextField(verbose_name=': متن مورد نظر')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True, )

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import PostComment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=80, label='نام خود را وارد کنید',
                           widget=forms.TextInput(attrs={'class': 'form-control form text-right'}))
    email = forms.EmailField(label='ایمیل خود را وارد کنید',
                             widget=forms.EmailInput(attrs={'class': 'form-control text-right'}))
    to = forms.EmailField(label='ایمیل خود را وارد کنید',
                          widget=forms.EmailInput(attrs={'class': 'form-control text-right'}))
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control text-right'}),
                               label='متن نظر خود را وارد کنید')


class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ['name', 'email', 'body']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control text-right', 'placeholder': 'نام خود را وارد کنید'}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control text-right', 'placeholder': 'ایمیل خود را وارد کنید'}),
            'body': forms.Textarea(
                attrs={'class': 'form-control text-right', 'placeholder': 'متن نظر خود را وارد کنید'}),

        }


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, PostComment, HomeBanner, AboutMe
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity


# Create your views here.
def index(request):
    main = get_object_or_404(HomeBanner)
    about_me = get_object_or_404(AboutMe)
    context = {
        'main': main,
        'about_me': about_me
    }
    return render(request, 'blog/index/index.html', context)


def about_me_page(request):
    return render(request, 'blog/index/about.html')


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug, )
        post_list = post_list.filter(tags__in=[tag])
    for post in post_list:
        post.total_comments = post.comments.count()
    # Pagination with 3 post pre page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page')
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    all_tags = Tag.objects.filter(post__in=post_list).distinct()
    context = {
        'posts': posts,
        'tag': tag,
        'all_tags': all_tags

    }
    return render(request, 'blog/post/list.html', context)


def post_detail(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', 'publish')[:4]
    comment_count = comments.count()
    # Check if 'INSERT_IMAGE_HERE' exists in the content
    if 'INSERT_IMAGE_HERE' in post.body:
        # Split the body into two parts based on the 'INSERT_IMAGE_HERE' marker
        body_parts = post.body.split('INSERT_IMAGE_HERE')
        content_before_image = body_parts[0]  # Content before the image
        content_after_image = body_parts[1]  # Content after the image
        has_image = True
    else:
        content_before_image = post.body
        content_after_image = None
        has_image = False
    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'similar_posts': similar_posts,
        'comment_count': comment_count,
        'content_before_image': content_before_image,
        'content_after_image': content_after_image,
        'has_image': has_image,
    }
    return render(request, 'blog/post/2.html', context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'codepython3.12@gmail.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'post': post,
        'form': form,
        'sent': sent,
    }
    return render(request, 'blog/post/share.html', context)


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    context = {
        'post': post,
        'form': form,
        'comment': comment,
    }
    return render(request, 'blog/post/comment.html', context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(similarity=TrigramSimilarity('title', query), ).filter(
                similarity__gt=0.1).order_by('-similarity')
    context = {
        'form': form,
        'query': query,
        'results': results
    }
    return render(request, 'blog/post/search.html', context)

blog/templates/blog/post/2.html
{% extends 'blog/base.html' %}
{% load static %}
{% load social_share %}
{% load hitcount_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block body %}

    <!--================ Start Banner Area =================-->
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="container">
                <div class="banner_content text-center">
                    <h2>Blog Details</h2>
                    <div class="page_link">
                        <a href="index.html">Home</a>
                        <a href="blog.html">Blog</a>
                        <a href="single-blog.html">Blog Details</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================ End Banner Area =================-->

    <!--================Blog Area =================-->
    <section class="blog_area single-post-area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post row">
                        <div class="col-lg-12">
                            <div class="feature-img">
                                <img class="img-fluid" src="{% static 'img/blog/feature-img1.jpg' %}" alt="">
                            </div>
                        </div>
                        <div class="col-lg-3  col-md-3">
                            <div class="blog_info text-right">
                                <div class="post_tag">
                                    <a href="#">{{ post.tags.all|join:', ' }}</a>
                                    {#                                    <a class="active" href="#">Technology,</a>#}

                                </div>
                                <ul class="blog_meta list">
                                    <li><a href="#">{{ post.author }}<i class="lnr lnr-user"></i></a></li>
                                    <li><a href="#">{{ post.jpublish }}<i class="lnr lnr-calendar-full"></i></a>
                                    </li>
                                    <li><a href="#">{% get_hit_count for post %}<i class="lnr lnr-eye"></i></a></li>
                                    <li><a href="#">{{ comment_count }} : نظرات <i class="lnr lnr-bubble"></i></a></li>
                                </ul>
                                <ul class="social-links">
                                    <li><a href="#"><i class="fab fa-whatsapp"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fab fa-telegram"></i></a></li>
                                    <li><a href="#"><i class="fas fa-envelope"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="quotes">
                                {{ post.quotes|safe }}
                            </div>
                            <div class="row">
                                {% if post.image_one %}
                                    <div class="col-6">
                                        <img class="img-fluid" src="{{ post.image_one.url }}" alt="{{ post.title }}">
                                    </div>
                                {% endif %}
                                {% if post.image_two %}
                                    <div class="col-6">
                                        <img class="img-fluid" src="{{ post.image_two.url }}" alt="">
                                    </div>
                                {% endif %}
                            </div>
                            {% if post.body %}
                                <div class="col-lg-12 mt-25">
                                    {% if 'INSERT_IMAGE_HERE' in post.body %}
                                        <p>{{ content_before_image|safe }}</p>
                                        {% if post.image %}
                                            <img class="img-fluid" src="{{ post.image.url }}" alt="{{ post.title }}">
                                        {% endif %}
                                        <p>{{ content_after_image|safe }}</p>
                                    {% else %}
                                        <p>{{ post.body|safe }}</p>
                                    {% endif %}
                                </div>
                            {% endif %}
                        </div>


                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"
                               role="button"
                               aria-haspopup="true"
                               aria-expanded="false">به اشتراک گذاری</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link"
                                                        href="{% url 'blog:post_share' post.id %}">ایمیل</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link"
                                       href="">{% post_to_telegram post.get_absolute_url link_text='تلگرام' %}
                                    </a>
                                </li>

                                <li class="nav-item"><a class="nav-link"
                                                        href=""> {% post_to_whatsapp post.get_absolute_url link_text='واتس اپ ' %}</a>
                                </li>
                            </ul>
                        </li>
                    </div>
                </div>
            </div>
        </div>
        <div class="comments-area">
            {% with comments.count as total_comments %}
                <h4>{{ total_comments }} تعداد کامنت ها </h4>
            {% endwith %}
            <div class="comment-list">
                <div class="single-comment justify-content-between d-flex">
                    <div class="user justify-content-between d-flex">

                        <div class="desc">
                            {% for comment in comments %}
                                <h5><a href="#">{{ comment.name }} کامنت نوشته شده توسط </a></h5>
                                <p class="date">{{ comment.created }}</p>
                                <p class="comment">
                                    {{ comment.body|linebreaks }}
                                </p>
                            {% empty %}
                                <p>'هنوز کامنتی وجود ندارد.'</p>
                                </div>
                            {% endfor %}
                    </div>
                </div>
                <div class="reply-btn">
                    <a href="" class="btn-reply text-uppercase">reply</a>
                </div>
            </div>
        </div>

        <div class="comment-form">
            <h4>Leave a Reply</h4>
            {% include 'blog/post/includes/comment_form.html' %}
        </div>
        </div>
        {% include 'blog/post/includes/sidebar.html' %}
        </div>
        </div>

    </section>
    <!--================Blog Area =================-->

{% endblock body %}

blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}
{% block title %}Add a comment{% endblock %}
{% block body %}
    <section class="blog_area single-post-area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post row">
                        <div class="col-lg-9 col-md-9 blog_details text-center ">
                            {% if comment %}
                                <h2>Your comment add successfully</h2>
                                <a href="{{ post.get_absolute_url }}">Back to post</a>
                            {% else %}
                                {% include 'blog/post/includes/comment_form.html' %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>

    {% endfor %}

</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load hitcount_tags %}
{% block title %}صفحه اصلی بلاگ{% endblock %}

{% block body %}
    <!--================ Start Banner Area =================-->
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="container">
                <div class="banner_content text-center">
                    <h2> بلاگ </h2>
                    <div class="page_link">
                        <a href="{% url 'blog:index' %}"> خانه / </a>
                        <a href="{% url 'blog:post_list' %}"> بخش بلاگ </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================ End Banner Area =================-->

    <!--================Blog Area =================-->
    <section class="blog_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="blog_left_sidebar">
                        {% if tag %}
                            <h2 class="text-center">پست هایی که تگ "{{ tag.name }}" دارند </h2>
                        {% endif %}
                        <article class="row blog_item">
                            {% for post in posts %}
                                <div class="col-md-3">
                                    <div class="blog_info text-right">
                                        <div class="post_tag">
                                            <i class="fa fa-hashtag">
                                                تگ:
                                                {% for tag in post.tags.all %}
                                                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                                                        {{ tag.name }}
                                                    </a>

                                                    {% if not forloop.last %}, {% endif %}
                                                {% endfor %}
                                            </i>
                                            {#<a class="active" href="#">Technology,</a>#}

                                        </div>
                                        <ul class="blog_meta list">
                                            <li><a href="#">{{ post.author }}<i class="lnr lnr-user"></i></a></li>
                                            <li><a href="#">{{ post.jpublish }}<i
                                                    class="lnr lnr-calendar-full"></i></a></li>
                                            <li><a href="#">{% get_hit_count for post %}<i class="lnr lnr-eye"></i></a>
                                            </li>
                                            <li><a href="#">{{ post.total_comments }} :تعداد نظرات <i class="lnr lnr-bubble"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <div class="blog_post">
                                        <img src="img/blog/main-blog/m-blog-1.jpg" alt="">
                                        <div class="blog_details">
                                            <a href="{{ post.get_absolute_url }}"><h2>{{ post.title }}</h2>
                                            </a>
                                            <p>{{ post.body|safe|truncatewords_html:30 }}</p>
                                            <a href="{{ post.get_absolute_url }}"
                                               class="primary_btn"><span>خواندن بیشتر</span></a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </article>
                        {% include "pagination.html" with page=posts %}
                    </div>
                </div>
              {% include 'blog/post/includes/sidebar.html' %}
            </div>

        </div>
    </section>
    <!--================Blog Area =================-->
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block body %}
<section class="blog_categorie_area section_gap_top">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                {% if query %}
                    <h1>Posts containing "{{ query }}"</h1>
                    <h3>
                        {% with result.count as total_result %}
                            Found {{ total_result }} result {{ total_result|pluralize }}
                        {% endwith %}
                    </h3>
                    {% for post in results %}
                        <h4>
                            <a href="{{ post.get_absolute_url }}">
                                {{ post.title }}
                            </a>
                        </h4>
                        {{ post.body|safe|truncatewords_html:12 }}
                    {% empty %}
                        <p>There are no results for your query.</p>
                    {% endfor %}
                    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
                {% else %}
                    <h1>Search for posts</h1>
                    <form method="get">
                        {{ form.as_p }}
                        <input type="submit" value="Search">
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block body %}
    {% if sent %}
        <section class="blog_area single-post-area section_gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 posts-list">
                        <div class="single-post row">
                             <div class="col-lg-9 col-md-9 blog_details text-center ">
                            <h1>ایمیل شما با موفقیت ارسال شد</h1>
                            <p>
                                پست {{ post.title }} با موفقیت به {{ form.cleaned_data.to }} ارسال شد
                            </p>
                                 <a class="button " href="{{ post.get_absolute_url }}">برگشت به صفحه قبل
                                 </a>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% else %}
        <h1>اشتراک گذاری "{{ post.title }}" با ایمیل </h1>
        <form class="comment-form" method="post">
        <div class="form-group ">
            {{ form.as_p }}
            {% csrf_token %}
            <input class="button btn-primary" type="submit" value="ارسال ایمیل ">
            </div>
        </form>
    {% endif %}
{% endblock %}